# Use postgres/example user/password credentials
version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TEST_SM
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres-data:
#version: '3.1'
#
#services:
#  db:
##    volumes:
##      - 01_stage/04_CreateShFile:/var/lib/data
#    ports:
#      - 5001:5432
#    image: postgres
#    container_name: postgresdb
#    restart: always
#    environment:
#      POSTGRES_USER: pgadmin
#      POSTGRES_PASSWORD: pgpassword
#    networks:
#      first_stage_net:
#
#  pgadmin:
#    image: dpage/pgadmin4
#    depends_on:
#      - db
#    ports:
#      - "5555:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#    restart: unless-stopped
#    networks:
#      first_stage_net:
##    volumes:
##      - 04_CreateShFile:/var/lib/pgadmin
#networks:
#  first_stage_net:
#    driver: bridge
